### PR TITLE
Replaced singularity with apptainer

### PR DESCRIPTION
**Pull request by mariavd**
Sorry for creating a second branch, I was editing the content from the browser. I'll clone it to my laptop and make commits to one branch.

### CODE REVIEW

**Comment by mariavd** [comment]
@yetulaxman  The example about creating a container might need to be rewritten completely. Do you have time for that?

**Review by yetulaxman — CHANGES_REQUESTED** [review]
Edited a few more changes to be compatible with Apptainer. There is one thing that is still not clear: when we use apptainer_wrapper (or even singularity_wrapper), the command is not recognising container image when explicitly passed an argument; I guess some $PATH variable is not properly set in recent changes ?.  These wrapper commands are working fine only after exporting $SING_IMAGE

**Comment by mariavd** [comment]
I hope we're not doing work in parallel. I started editing locally instead of github. In any case, these need to be tested. Do you have a computer with apptainer installed?

**Comment by yetulaxman** [comment]
> apptainer commands are working on Puhti so we can use it for testing

**Comment by mariavd** [comment]
But there are examples that require sudo rights.

**Comment by yetulaxman** [comment]
Ok. You are talking about building images from def files. Yes, those require sudo rights. we can probably install apptainer in cPouta and test them. I will look into this.

**Comment by mariavd** [comment]
Kylli has a pouta instance with installed singularity and sudo rights but an instance with apptainer would be nice, too.

**Comment by mariavd** [comment]
Should we switch the discussion to the other PR or merge the changes there and continue on this branch?

**Comment by rkronberg** [comment]
Are the changes here also in the other PR? I.e. should this PR be merged or just closed?

**Comment by mariavd** [comment]
I ended up making two branches with different modifications. I believe that this can be merged if @yetulaxman also confirms.

**Comment by yetulaxman** [comment]
> I ended up making two branches with different modifications. I believe that this can be merged if @yetulaxman also confirms.

yes. I think we can merge this

**Review by yetulaxman — APPROVED** [review]

**Pull request merged**
